### ISSUE TITLE
HF: Make the parameter configurable

### ISSUE THREAD

**Issue by davisjam** [SoftwareSystemsLaboratory/PTMTorrent#15]
https://github.com/SoftwareSystemsLaboratory/PTMTorrent/tree/main/ptm_torrent/huggingface

Changing the parameter requires editing a python file. Can we make it a command-line arg or an environment variable?

**Comment by NicholasSynovic** [comment]
I've made it an environment variable and added docs on how to change it. I'll merge my changes @davisjam
