### ISSUE TITLE
Modelhub storage?

### ISSUE THREAD

**Issue by davisjam** [SoftwareSystemsLaboratory/PTMTorrent#16]
"To download the entirety of the [Modelhub](https://modelhub.ai/) model hub requires nGB of storage."

"nGB": Update n and indicate the time of the measurement.

**Comment by davisjam** [comment]
(The same placeholder occurs in many of the READMEs).

I suggest that we delete this line from each of the per-hub READMEs and instead have a single table in the main README with an associated timestamp.

**Comment by NicholasSynovic** [comment]
I have removed the references from each individual README.md file. Arav is working on the table
