### ISSUE TITLE
HF downloader

### ISSUE THREAD

**Issue by davisjam** [SoftwareSystemsLaboratory/PTMTorrent#17]
Did we use this sequential downloader to do the downloading? I think we did some parallelism. Did we split it into many jobs each of which used the downloader?

If so, let's clarify that and describe what we did. That would help someone who wants to replicate.

**Comment by pjjajal** [comment]
I modified the source code to batch and split the repos we want to download into groups of 100 repos. These were written to txt files that are then read by the downloader and the repos in the batch are downloaded. I can make a PR if you would like @NicholasSynovic.

**Comment by davisjam** [comment]
OK, let's get the actual code up.
________________________________

**Comment by NicholasSynovic** [comment]
@pjjajal please make the pr

**Comment by pjjajal** [comment]
#24
